name: Deploy

on:
  push:
    branches:
      - master
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Running heroku
        uses: mtkumar123/MyDollarBot@v1.0.1 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mydollarbot-beta" #Must be unique in Heroku
          heroku_email: "ashwindasr@gmail.com"